brokers:
  producer1: "static:(tcp://producer1:61616)"
  producer2: "static:(tcp://producer2:61616)"
  consumer1: "static:(tcp://consumer1:61616)"
  consumer2: "static:(tcp://consumer2:61616)"
  consumer3: "static:(tcp://consumer3:61616)"

networks:
  common_configuration:
    set_broker_name: "false"
    queue:
      conduit_subscriptions: "false"
      consumer_ttl: "1"
      duplex: "true"
      message_ttl: "-1"
      user_name: "admin"
    topic:
      conduit_subscriptions: "true"
      consumer_ttl: "1"
      duplex: "true"
      message_ttl: "-1"
      user_name: "admin"

  network_connector:
    producer1:
      to:
        - consumer1
        - consumer2
        - consumer3
      config:
        queue:
          duplex: "false"
        topic:
          duplex: "false"
    producer2:
      to:
        - consumer1
        - consumer2
        - consumer3
      config:
        queue:
          duplex: "false"
        topic:
          duplex: "false"
    consumer1:
      to:
        - consumer2
    consumer2:
      to:
        - consumer3
    consumer3:
      to:
        - consumer1



