brokers:
  broker1: "static:(tcp://broker1:61616)"
  broker2: "static:(tcp://broker2:61616)"
  broker3: "static:(tcp://broker3:61616)"
  broker4: "static:(tcp://broker4:61616)"
  broker5: "static:(tcp://broker5:61616)"

networks:
  common_configuration:
    conduit_subscriptions: "true"
    consumer_ttl: "1"
    duplex: "false"
    message_ttl: "-1"
    user_name: "admin"

  network_connector:
    broker1:
      to:
        - broker2
        - broker3
        - broker4
        - broker5
    broker2:
      to:
        - broker1
        - broker3
        - broker4
        - broker5
    broker3:
      to:
        - broker1
        - broker2
        - broker4
        - broker5
    broker4:
      to:
        - broker1
        - broker2
        - broker3
        - broker5
    broker5:
      to:
        - broker1
        - broker2
        - broker3
        - broker4

