brokers:
  hub: "static:(tcp://hub:61616)"
  node1: "static:(tcp://node1:61616)"
  node2: "static:(tcp://node2:61616)"
  node3: "static:(tcp://node3:61616)"
  node4: "static:(tcp://node4:61616)"

networks:
  common_configuration:
    conduit_subscriptions: "true"
    consumer_ttl: "1"
    duplex: "true"
    message_ttl: "-1"
    physical_name: ">"
    user_name: "admin"

  network_connector:
    hub:
      to: # Leave empty because there is no connection
    node1:
      to:
        - hub
    node2:
      to:
        - hub
    node3:
      to:
        - hub
    node4:
      to:
        - hub
